services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mbg_backend
    restart: always
    environment:
      DB_DSN: "kassaone:f2RZScqZe5JOmvd3xeBvQlkpo4Vutjm9@tcp(mbg_mysql:3306)/mbg_management?charset=utf8mb4&parseTime=True&loc=Local"
    volumes:
      - ./dist:/root/dist
    networks:
      - mbg_network

  backend_dev:
    build:
      context: ${DEV_CONTEXT:-.}
      dockerfile: Dockerfile
    container_name: mbg_backend_dev
    restart: always
    environment:
      DB_DSN: "kassaone:f2RZScqZe5JOmvd3xeBvQlkpo4Vutjm9@tcp(mbg_mysql:3306)/mbg_management_dev?charset=utf8mb4&parseTime=True&loc=Local"
      PORT: "8081"
    volumes:
      - ${DEV_CONTEXT:-.}/dist:/root/dist
    networks:
      - mbg_network

  caddy:
    image: caddy:latest
    container_name: mbg_caddy
    restart: always
    volumes:
      - ./backend/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend
      - backend_dev
    networks:
      - mbg_network

networks:
  mbg_network:
    external: true

volumes:
  caddy_data:
  caddy_config:
