services:
  db:
    image: mysql:8.0
    container_name: mbg_mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mbg_backend
    restart: always
    depends_on:
      - db
    environment:
      DB_DSN: ${DB_DSN}

  backend_dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mbg_backend_dev
    restart: always
    environment:
      DB_DSN: "kassaone:${MYSQL_PASSWORD}@tcp(db:3306)/mbg_management_dev?charset=utf8mb4&parseTime=True&loc=Local"
      PORT: "8081"
    depends_on:
      - db

  caddy:
    image: caddy:latest
    container_name: mbg_caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./backend/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend
      - backend_dev

volumes:
  mysql_data:
  caddy_data:
  caddy_config:
