services:
  backend_dev:
    build: .
    container_name: mbg_backend_dev
    expose:
      - "8081"
    environment:
      DB_DSN: "kassaone:Piblajar2020@tcp(mbg_mysql:3306)/mbg_management_dev?charset=utf8mb4&parseTime=True&loc=Local"
      PORT: "8081"
    networks:
      - mbg_management_default

networks:
  mbg_management_default:
    external: true
